config/routes.rb
Rails.application.routes.draw do
  root to: "application#home"

  resources :members, except: :index
  resource :membership_inquiry, only: [:new, :create, :show]
  resource :membership_confirmation, only: [:new, :create, :show]
  resources :vote_requests, only: [:new, :create]

  namespace :admin do
    resources :members
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  EXPORTABLE_FIELDS = %w[
    id
    full_name
    joined_at
    email
    phone
    data
    last_active_at
    created_at
    updated_at
  ]

  has_secure_token :voting_token

  before_create :set_joined_at
  after_create :reset_token!

  def confirm!
    update! last_active_at: Time.current
  end

  def reset_token!
    update!(
      token: SecureRandom.hex,
      token_updated_at: Time.current,
      last_active_at: Time.current
    )
  end

  def join_date
    joined_at.to_date
  end

  private

  def set_joined_at
    self.joined_at ||= Time.current
  end
end

app/controllers/admin/members_controller.rb
require "csv"

module Admin
  class MembersController < ::MembersController
    http_basic_authenticate_with(
      name: ENV.fetch("AUTH_NAME") { "secretary" },
      password: ENV.fetch("AUTH_PASSWORD") {
        Rails.logger.info("You have not set a password for the admin area")
        SecureRandom.hex
      }
    )

    def index
      @members = Member.all.order(updated_at: :desc)

      respond_to do |format|
        format.html
        format.csv do
          csv_content = CSV.generate(headers: true) do |csv|
            csv << Member::EXPORTABLE_FIELDS

            @members.pluck(*Member::EXPORTABLE_FIELDS).each { |member| csv << member }
          end

          send_data csv_content.force_encoding("UTF-8"), type: "text/csv"
        end
      end
    end

    def create
      @member = Member.new(member_params)
      @member.save
      respond_with :admin, @member
    end

    def update
      @member.update(member_params)
      respond_with :admin, @member
    end

    private

    def token_valid?
      true
    end

    def member_params
      params.require(:member).permit(:full_name, :email, :phone, :joined_at)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  responders :flash

  before_action :set_mailer_host

  private

  def set_mailer_host
    ActionMailer::Base.default_url_options = {
      host: request.host_with_port
    }
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  InvalidToken = Class.new(StandardError)
  TOKEN_EXPIRY = 24.hours

  rescue_from InvalidToken, with: :render_token_error

  before_action :set_member, only: [:show, :edit, :update]

  respond_to :html

  def show
    respond_with @member
  end

  def new
    @member = Member.new
    respond_with @member
  end

  def edit
    respond_with @member
  end

  def create
    @member = MembershipApplication.new(member_params)
    @member.save
    respond_with @member, location: [@member, token: @member.token]
  end

  def update
    @member = @member.becomes(MembershipApplication)
    @member.update(member_params)
    respond_with @member
  end

  private

  def set_member
    @member = Member.find(params[:id])
    raise InvalidToken unless token_valid?
  end

  def member_params
    params.require(:member).permit(:full_name, :email, :phone)
  end

  def token
    session[:token] = params[:token] || session[:token]
  end

  def token_valid?
    @member.token == token &&
      @member.token_updated_at > TOKEN_EXPIRY.ago
  end

  def render_token_error
    render :token_error
  end
end

app/controllers/membership_confirmations_controller.rb
class MembershipConfirmationsController < ApplicationController
  respond_to :html

  def new
    @confirm = MembershipConfirmation.new
  end

  def create
    @confirm = MembershipConfirmation.new(confirmation_params)
    @confirm.confirm
    respond_with @confirm, location: :membership_confirmation
  end

  private

  def confirmation_params
    params.require(:membership_confirmation).permit(:email)
  end
end

app/controllers/membership_inquiries_controller.rb
class MembershipInquiriesController < ApplicationController
  respond_to :html

  def new
    @inquiry = MembershipInquiry.new
  end

  def create
    @inquiry = MembershipInquiry.new(inquiry_params)
    @inquiry.deliver_email
    respond_with @inquiry, location: membership_inquiry_path(@inquiry)
  end

  private

  def inquiry_params
    params.require(:membership_inquiry).permit(:email)
  end
end

app/controllers/vote_requests_controller.rb
class VoteRequestsController < ApplicationController
  before_action :verify_voting_enabled

  def new
  end

  def create
    member = Member.find_by(email: params.require(:email))

    if member
      MembershipMailer.vote_request(member).deliver_now
    else
      # Simulate a small delay to prevent membership disclosure via timing
      # attacks.
      sleep rand(0.1..0.3)
    end
  end

  private

  def verify_voting_enabled
    return if helpers.voting_enabled?

    raise "Voting not enabled"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_attribute(model, attr, &block)
    attr_name = model.class.human_attribute_name(attr)
    value = block_given? ? capture(&block) : model[attr]

    content_tag(:p) do
      safe_join [
        content_tag(:strong, "#{attr_name}:"),
        value
      ], " "
    end
  end

  def time_ago_span(time)
    return unless time

    content_tag(:span, time_ago_in_words(time), title: time)
  end

  def voting_enabled?
    Rails.configuration.vote_url_template.present?
  end
end

app/views/admin/members/_form.html.erb
<%= simple_form_for([:admin, member]) do |f| %>
  <%= f.input :full_name %>
  <%= f.input :joined_at, as: :date %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.button :submit %>
<% end %>

<%= link_to t(:cancel), [:admin, @member] %>

app/views/admin/members/_legal.en.html.erb
<p>
  This is a legal document. The secretary of
  <%= MembershipRegister.society_name %>
  is required to maintain this membership register
  and can be asked to provide it  if the society is audited.

  More details can be found on the
  <%= link_to 'societies website', 'http://www.societies.govt.nz/cms/incorporated-societies/running-a-society/what-records-should-you-keep' %>.
</p>

app/views/admin/members/index.html.erb
<div class="page-header">
  <h2><%= t '.page-title' %></h2>
</div>

<%= render 'legal' %>

<%= link_to t('.download-csv'), url_for(format: :csv), style: 'float:right' %>

<p>
  <strong><%= pluralize Member.count, Member.model_name.human %></strong>
  <%= link_to t('.new-member'), new_admin_member_path %>
</p>

<table class='table'>
  <thead>
    <tr>
      <th><%= Member.human_attribute_name(:full_name) %></th>
      <th><%= Member.human_attribute_name(:joined) %></th>
      <th><%= Member.human_attribute_name(:email) %></th>
      <th><%= Member.human_attribute_name(:phone) %></th>
      <th><%= Member.human_attribute_name(:updated) %></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.full_name, [:admin, member] %></td>
        <td><%= member.join_date.to_fs(:long) %></td>
        <td><%= member.email %></td>
        <td><%= member.phone %></td>
        <td><%= time_ago_span(member.updated_at) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/members/show.html.erb
<div class="page-header">
  <h2><%= t '.page-title' %></h2>
</div>

<%= render 'details', member: @member %>

<p>
  <%= link_to t(:edit), edit_admin_member_path(@member) %>
  |
  <%= link_to t(:back), admin_members_path %>
</p>

app/views/application/home.en.html.erb
<div class="row">
  <% if voting_enabled? %>
    <div class="col-md-12">
      <h2>Voting now live</h2>
      <p>
        Voting for this year's AGM is available for members.
        <%= link_to 'Cast your vote…', new_vote_request_path %>
      </p>
    </div>
  <% end %>

  <div class="col-md-6">
    <div class="page-header">
      <h2>New Members</h2>
    </div>

    <p>
      This is Ruby New Zealand’s official membership register.
      Membership isn’t very fancy, but it does allow you to have your say about the committee
      and other society matters at the AGM held each year.
      <br>
      <%= link_to 'Register for membership…', new_member_path %>
    </p>
  </div>
  <div class="col-md-6">
    <div class="page-header">
      <h2>Existing Members</h2>
    </div>

    <p>
      Already a member and need to update your details? Not sure if you're a member?<br>
      <%= link_to 'Check existing membership…', new_membership_inquiry_path %>
    </p>

    <br>

    <p>
      Want to confirm your continued existing membership to the Ruby New Zealand Society?<br>
      <%= link_to 'Confirm existing membership…', new_membership_confirmation_path %>
    </p>
  </div>
</div>

app/views/application/home.html.erb
<p>
  This is an overview of Ruby New Zealand’s official membership register. If you’d like to sign up, please fill out the
  <%= link_to 'membership registration form', new_member_path %>.
  Membership isn’t very fancy, but it does allow you to have your say about the committee
  and other society matters at the AGM held at Rails Camp each year.
</p>

<p>
  <em>
    If you have an questions, feedback, or problems
    please email <a href="mailto:secretary@ruby.nz">secretary@ruby.nz</a>.
  </em>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Official Membership Register | Ruby New Zealand Incorporated</title>
    <%= favicon_link_tag "logo.png" %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <header>
      <div class="container">

          <h1>
            <a href="/">
            Official Membership Register
            <small>Ruby New Zealand Incorporated</small>
            </a>
          </h1>

      </div>
    </header>

    <div class="container">
      <%= yield %>
    </div>

    <footer class='page-footer'>
      <div class="container">
        If you have any questions, feedback, or problems,
        please email <a href="mailto:secretary@ruby.nz">secretary@ruby.nz</a>
        or raise a <%= link_to "pull request", ENV.fetch("REPO_URL") { "https://github.com/rubynz/membership-register" } %>.
      </div>
    </footer>

    <%= javascript_include_tag "application", defer: true %>
    <%= csrf_meta_tags %>
  </body>
</html>

app/views/members/_details.html.erb
<%= render_attribute member, :full_name %>
<%= render_attribute member, :joined_at do %>
  <%= member.join_date.to_fs(:long) %>
<% end %>
<%= render_attribute member, :email %>
<%= render_attribute member, :phone %>

app/views/members/_form.html.erb
<%= simple_form_for(member) do |f| %>
  <%= f.input :full_name %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Cancel Changes', @member if @member.persisted? %>

app/views/members/edit.html.erb
<div class="page-header">
  <h2><%= t '.page-title' %></h2>
</div>

<%= render 'form', member: @member %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.full_name %></td>
        <td><%= member.email %></td>
        <td><%= member.address %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<div class="page-header">
  <h2>Membership Registration</h2>
</div>
<%= render 'form', member: @member %>

app/views/members/show.html.erb
<div class="page-header">
  <h2>Membership Details</h2>
</div>

<%= render 'details', member: @member %>

<p><%= link_to 'Update Details…', edit_member_path(@member) %></p>

<p class="small text-muted">
  If you would like to cancel your membership,
  please email <a href="mailto:secretary@ruby.nz">secretary@ruby.nz</a>.
</p>

app/views/members/token_error.html.erb
<div class="alert alert-warning">
  <p>
    <span class="glyphicon glyphicon-ban-circle"></span>
    <%= t '.message' %>
  </p>
</div>

<%= render 'membership_inquiries/form', inquiry: MembershipInquiry.new(email: @member.email) %>

app/views/membership_confirmations/_form.html.erb
<p>
  <%= t '.instructions' %>

  <%= simple_form_for(confirm, url: membership_confirmation_path) do |f| %>
    <%= f.input :email, placeholder: :translate %>
    <%= f.button :submit %>
  <% end %>
</p>

app/views/membership_confirmations/new.html.erb
<div class="page-header">
  <h2>Membership Confirmation</h2>
</div>

<%= render 'membership_confirmations/form', confirm: @confirm %>

app/views/membership_confirmations/show.html.erb
<div class="page-header">
  <h2>Membership Confirmation</h2>
</div>

<div class="alert alert-success">
  <p>
    <span class="glyphicon glyphicon-ok"></span>
    <%= flash[:notice] %>
  </p>
</div>

app/views/membership_inquiries/_form.html.erb
<p>
  <%= t '.instructions' %>

  <%= simple_form_for(inquiry, url: membership_inquiry_path) do |f| %>
    <%= f.input :email, placeholder: :translate %>
    <%= f.button :submit %>
  <% end %>
</p>

app/views/membership_inquiries/new.html.erb
<div class="page-header">
  <h2>Membership Inquiry</h2>
</div>

<%= render 'membership_inquiries/form', inquiry: @inquiry %>

app/views/membership_inquiries/show.html.erb
<div class="page-header">
  <h2>Membership Inquiry</h2>
</div>

<div class="alert alert-success">
  <p>
    <span class="glyphicon glyphicon-ok"></span>
    <%= flash[:notice] %>
  </p>
</div>

app/views/vote_requests/create.html.erb
<h2>Thanks!</h2>

<p>If you have a membership, you should shortly receive a unique voting link to your email address.</p>

<p>Allow a few minutes for the email to arrive.</p>

<p>Please keep this link secret.</p>

app/views/vote_requests/new.html.erb
<h2>Cast your vote</h2>

<p>Enter your registered email address to receive your unique voting link:</p>

<%= form_with url: vote_requests_url, method: :post do |f| %>
  <div class="form-group email required">
    <%= f.label :email, class: 'control-label' %>
    <%= f.email_field :email, class: 'form-control' %>
    <p>Double-check your email address. To protect member privacy, we won't tell you if it's valid.</p>
  </div>

  <%= f.submit 'Send voting link', class: 'btn btn-default' %>
<% end %>